package com.kindustry.jpa.model;

import java.io.Serializable;
import java.util.Date;

public class Nyukin implements Serializable {

  /**
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database table MRNDBUSER.NYUKIN
   *
   * @mbg.generated Fri Nov 27 15:13:03 JST 2020
   */
  private static final long serialVersionUID = 1L;

  /**
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column MRNDBUSER.NYUKIN.KANJANO
   *
   * @mbg.generated Fri Nov 27 15:13:03 JST 2020
   */
  private Integer kanjano;

  /**
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column MRNDBUSER.NYUKIN.HKKUMI
   *
   * @mbg.generated Fri Nov 27 15:38:16 JST 2020
   */
  private Short hkkumi;

  /**
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column MRNDBUSER.NYUKIN.SINRYODATE
   *
   * @mbg.generated Fri Nov 27 15:38:16 JST 2020
   */
  private Date sinryodate;

  /**
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column MRNDBUSER.NYUKIN.RAIINKAISU
   *
   * @mbg.generated Fri Nov 27 15:38:16 JST 2020
   */
  private Short raiinkaisu;

  /**
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column MRNDBUSER.NYUKIN.NYUKINDATE
   *
   * @mbg.generated Fri Nov 27 15:38:16 JST 2020
   */
  private Date nyukindate;

  /**
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column MRNDBUSER.NYUKIN.HUTANKIN
   *
   * @mbg.generated Fri Nov 27 15:38:16 JST 2020
   */
  private Long hutankin;

  /**
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column MRNDBUSER.NYUKIN.JIHIKIN
   *
   * @mbg.generated Fri Nov 27 15:38:16 JST 2020
   */
  private Long jihikin;

  /**
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column MRNDBUSER.NYUKIN.NYUKINGAKU
   *
   * @mbg.generated Fri Nov 27 15:38:16 JST 2020
   */
  private Long nyukingaku;

  /**
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column MRNDBUSER.NYUKIN.TYOSEIKIN
   *
   * @mbg.generated Fri Nov 27 15:38:16 JST 2020
   */
  private Long tyoseikin;

  /**
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column MRNDBUSER.NYUKIN.JIBAISEIKYUKBN
   *
   * @mbg.generated Fri Nov 27 15:38:16 JST 2020
   */
  private Short jibaiseikyukbn;

  /**
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column MRNDBUSER.NYUKIN.TEISEINYUKINKBN
   *
   * @mbg.generated Fri Nov 27 15:38:16 JST 2020
   */
  private Short teiseinyukinkbn;

  /**
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column MRNDBUSER.NYUKIN.OPKBN
   *
   * @mbg.generated Fri Nov 27 15:38:16 JST 2020
   */
  private Short opkbn;

  /**
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column MRNDBUSER.NYUKIN.NYUKINCOMM
   *
   * @mbg.generated Fri Nov 27 15:38:16 JST 2020
   */
  private String nyukincomm;

  /**
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column MRNDBUSER.NYUKIN.KOUSINTIME
   *
   * @mbg.generated Fri Nov 27 15:38:16 JST 2020
   */
  private Date kousintime;

  /**
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column MRNDBUSER.NYUKIN.ROSAISEIKYUKBN
   *
   * @mbg.generated Fri Nov 27 15:38:16 JST 2020
   */
  private Short rosaiseikyukbn;

  /**
   *
   * This field was generated by MyBatis Generator.
   * This field corresponds to the database column MRNDBUSER.NYUKIN.NYUKINTIME
   *
   * @mbg.generated Fri Nov 27 15:38:16 JST 2020
   */
  private Date nyukintime;

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column MRNDBUSER.NYUKIN.KANJANO
   *
   * @return the value of MRNDBUSER.NYUKIN.KANJANO
   *
   * @mbg.generated Fri Nov 27 15:38:16 JST 2020
   */
  public Integer getKanjano() {
    return kanjano;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column MRNDBUSER.NYUKIN.KANJANO
   *
   * @param kanjano the value for MRNDBUSER.NYUKIN.KANJANO
   *
   * @mbg.generated Fri Nov 27 15:38:16 JST 2020
   */
  public void setKanjano(Integer kanjano) {
    this.kanjano = kanjano;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column MRNDBUSER.NYUKIN.HKKUMI
   *
   * @return the value of MRNDBUSER.NYUKIN.HKKUMI
   *
   * @mbg.generated Fri Nov 27 15:38:16 JST 2020
   */
  public Short getHkkumi() {
    return hkkumi;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column MRNDBUSER.NYUKIN.HKKUMI
   *
   * @param hkkumi the value for MRNDBUSER.NYUKIN.HKKUMI
   *
   * @mbg.generated Fri Nov 27 15:38:16 JST 2020
   */
  public void setHkkumi(Short hkkumi) {
    this.hkkumi = hkkumi;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column MRNDBUSER.NYUKIN.SINRYODATE
   *
   * @return the value of MRNDBUSER.NYUKIN.SINRYODATE
   *
   * @mbg.generated Fri Nov 27 15:38:16 JST 2020
   */
  public Date getSinryodate() {
    return sinryodate;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column MRNDBUSER.NYUKIN.SINRYODATE
   *
   * @param sinryodate the value for MRNDBUSER.NYUKIN.SINRYODATE
   *
   * @mbg.generated Fri Nov 27 15:38:16 JST 2020
   */
  public void setSinryodate(Date sinryodate) {
    this.sinryodate = sinryodate;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column MRNDBUSER.NYUKIN.RAIINKAISU
   *
   * @return the value of MRNDBUSER.NYUKIN.RAIINKAISU
   *
   * @mbg.generated Fri Nov 27 15:38:16 JST 2020
   */
  public Short getRaiinkaisu() {
    return raiinkaisu;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column MRNDBUSER.NYUKIN.RAIINKAISU
   *
   * @param raiinkaisu the value for MRNDBUSER.NYUKIN.RAIINKAISU
   *
   * @mbg.generated Fri Nov 27 15:38:16 JST 2020
   */
  public void setRaiinkaisu(Short raiinkaisu) {
    this.raiinkaisu = raiinkaisu;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column MRNDBUSER.NYUKIN.NYUKINDATE
   *
   * @return the value of MRNDBUSER.NYUKIN.NYUKINDATE
   *
   * @mbg.generated Fri Nov 27 15:38:16 JST 2020
   */
  public Date getNyukindate() {
    return nyukindate;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column MRNDBUSER.NYUKIN.NYUKINDATE
   *
   * @param nyukindate the value for MRNDBUSER.NYUKIN.NYUKINDATE
   *
   * @mbg.generated Fri Nov 27 15:38:16 JST 2020
   */
  public void setNyukindate(Date nyukindate) {
    this.nyukindate = nyukindate;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column MRNDBUSER.NYUKIN.HUTANKIN
   *
   * @return the value of MRNDBUSER.NYUKIN.HUTANKIN
   *
   * @mbg.generated Fri Nov 27 15:38:16 JST 2020
   */
  public Long getHutankin() {
    return hutankin;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column MRNDBUSER.NYUKIN.HUTANKIN
   *
   * @param hutankin the value for MRNDBUSER.NYUKIN.HUTANKIN
   *
   * @mbg.generated Fri Nov 27 15:38:16 JST 2020
   */
  public void setHutankin(Long hutankin) {
    this.hutankin = hutankin;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column MRNDBUSER.NYUKIN.JIHIKIN
   *
   * @return the value of MRNDBUSER.NYUKIN.JIHIKIN
   *
   * @mbg.generated Fri Nov 27 15:38:16 JST 2020
   */
  public Long getJihikin() {
    return jihikin;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column MRNDBUSER.NYUKIN.JIHIKIN
   *
   * @param jihikin the value for MRNDBUSER.NYUKIN.JIHIKIN
   *
   * @mbg.generated Fri Nov 27 15:38:16 JST 2020
   */
  public void setJihikin(Long jihikin) {
    this.jihikin = jihikin;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column MRNDBUSER.NYUKIN.NYUKINGAKU
   *
   * @return the value of MRNDBUSER.NYUKIN.NYUKINGAKU
   *
   * @mbg.generated Fri Nov 27 15:38:16 JST 2020
   */
  public Long getNyukingaku() {
    return nyukingaku;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column MRNDBUSER.NYUKIN.NYUKINGAKU
   *
   * @param nyukingaku the value for MRNDBUSER.NYUKIN.NYUKINGAKU
   *
   * @mbg.generated Fri Nov 27 15:38:16 JST 2020
   */
  public void setNyukingaku(Long nyukingaku) {
    this.nyukingaku = nyukingaku;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column MRNDBUSER.NYUKIN.TYOSEIKIN
   *
   * @return the value of MRNDBUSER.NYUKIN.TYOSEIKIN
   *
   * @mbg.generated Fri Nov 27 15:38:16 JST 2020
   */
  public Long getTyoseikin() {
    return tyoseikin;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column MRNDBUSER.NYUKIN.TYOSEIKIN
   *
   * @param tyoseikin the value for MRNDBUSER.NYUKIN.TYOSEIKIN
   *
   * @mbg.generated Fri Nov 27 15:38:16 JST 2020
   */
  public void setTyoseikin(Long tyoseikin) {
    this.tyoseikin = tyoseikin;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column MRNDBUSER.NYUKIN.JIBAISEIKYUKBN
   *
   * @return the value of MRNDBUSER.NYUKIN.JIBAISEIKYUKBN
   *
   * @mbg.generated Fri Nov 27 15:38:16 JST 2020
   */
  public Short getJibaiseikyukbn() {
    return jibaiseikyukbn;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column MRNDBUSER.NYUKIN.JIBAISEIKYUKBN
   *
   * @param jibaiseikyukbn the value for MRNDBUSER.NYUKIN.JIBAISEIKYUKBN
   *
   * @mbg.generated Fri Nov 27 15:38:16 JST 2020
   */
  public void setJibaiseikyukbn(Short jibaiseikyukbn) {
    this.jibaiseikyukbn = jibaiseikyukbn;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column MRNDBUSER.NYUKIN.TEISEINYUKINKBN
   *
   * @return the value of MRNDBUSER.NYUKIN.TEISEINYUKINKBN
   *
   * @mbg.generated Fri Nov 27 15:38:16 JST 2020
   */
  public Short getTeiseinyukinkbn() {
    return teiseinyukinkbn;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column MRNDBUSER.NYUKIN.TEISEINYUKINKBN
   *
   * @param teiseinyukinkbn the value for MRNDBUSER.NYUKIN.TEISEINYUKINKBN
   *
   * @mbg.generated Fri Nov 27 15:38:16 JST 2020
   */
  public void setTeiseinyukinkbn(Short teiseinyukinkbn) {
    this.teiseinyukinkbn = teiseinyukinkbn;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column MRNDBUSER.NYUKIN.OPKBN
   *
   * @return the value of MRNDBUSER.NYUKIN.OPKBN
   *
   * @mbg.generated Fri Nov 27 15:38:16 JST 2020
   */
  public Short getOpkbn() {
    return opkbn;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column MRNDBUSER.NYUKIN.OPKBN
   *
   * @param opkbn the value for MRNDBUSER.NYUKIN.OPKBN
   *
   * @mbg.generated Fri Nov 27 15:38:16 JST 2020
   */
  public void setOpkbn(Short opkbn) {
    this.opkbn = opkbn;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column MRNDBUSER.NYUKIN.NYUKINCOMM
   *
   * @return the value of MRNDBUSER.NYUKIN.NYUKINCOMM
   *
   * @mbg.generated Fri Nov 27 15:38:16 JST 2020
   */
  public String getNyukincomm() {
    return nyukincomm;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column MRNDBUSER.NYUKIN.NYUKINCOMM
   *
   * @param nyukincomm the value for MRNDBUSER.NYUKIN.NYUKINCOMM
   *
   * @mbg.generated Fri Nov 27 15:38:16 JST 2020
   */
  public void setNyukincomm(String nyukincomm) {
    this.nyukincomm = nyukincomm == null ? null : nyukincomm.trim();
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column MRNDBUSER.NYUKIN.KOUSINTIME
   *
   * @return the value of MRNDBUSER.NYUKIN.KOUSINTIME
   *
   * @mbg.generated Fri Nov 27 15:38:16 JST 2020
   */
  public Date getKousintime() {
    return kousintime;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column MRNDBUSER.NYUKIN.KOUSINTIME
   *
   * @param kousintime the value for MRNDBUSER.NYUKIN.KOUSINTIME
   *
   * @mbg.generated Fri Nov 27 15:38:16 JST 2020
   */
  public void setKousintime(Date kousintime) {
    this.kousintime = kousintime;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column MRNDBUSER.NYUKIN.ROSAISEIKYUKBN
   *
   * @return the value of MRNDBUSER.NYUKIN.ROSAISEIKYUKBN
   *
   * @mbg.generated Fri Nov 27 15:38:16 JST 2020
   */
  public Short getRosaiseikyukbn() {
    return rosaiseikyukbn;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column MRNDBUSER.NYUKIN.ROSAISEIKYUKBN
   *
   * @param rosaiseikyukbn the value for MRNDBUSER.NYUKIN.ROSAISEIKYUKBN
   *
   * @mbg.generated Fri Nov 27 15:38:16 JST 2020
   */
  public void setRosaiseikyukbn(Short rosaiseikyukbn) {
    this.rosaiseikyukbn = rosaiseikyukbn;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method returns the value of the database column MRNDBUSER.NYUKIN.NYUKINTIME
   *
   * @return the value of MRNDBUSER.NYUKIN.NYUKINTIME
   *
   * @mbg.generated Fri Nov 27 15:38:16 JST 2020
   */
  public Date getNyukintime() {
    return nyukintime;
  }

  /**
   * This method was generated by MyBatis Generator.
   * This method sets the value of the database column MRNDBUSER.NYUKIN.NYUKINTIME
   *
   * @param nyukintime the value for MRNDBUSER.NYUKIN.NYUKINTIME
   *
   * @mbg.generated Fri Nov 27 15:38:16 JST 2020
   */
  public void setNyukintime(Date nyukintime) {
    this.nyukintime = nyukintime;
  }
}